export const models = {
   users: {
      lid: null,
      afk: -1,
      afkReason: '',
      afkObj: {},
      banned: false,
      ban_temporary: 0,
      ban_times: 0,
      premium: false,
      expired: 0,
      lastseen: 0,
      hit: 0,
      warning: 0,
      example: []
   },
   groups: {
      activity: 0,
      antidelete: true,
      antilink: false,
      antivirtex: false,
      antitagsw: true,
      filter: false,
      left: false,
      localonly: false,
      mute: false,
      viewonce: true,
      autosticker: true,
      member: {},
      text_left: '',
      text_welcome: '',
      welcome: true,
      expired: 0,
      stay: false
   },
   chats: {
      chat: 0,
      lastchat: 0,
      lastseen: 0
   },
   setting: {
      autobackup: false,
      autodownload: true,
      antispam: true,
      debug: false,
      notifier: false,
      error: [],
      hidden: [],
      pluginDisable: [],
      receiver: [],
      groupmode: false,
      sk_pack: 'New sticker',
      sk_author: 'Native Farguts',
      self: false,
      noprefix: false,
      multiprefix: true,
      prefix: ['_', '-', '×', '^'],
      toxic: ["ajg", "ajig", "anjas", "anjg", "anjim", "anjing", "anjrot", "anying", "asw", "autis", "babi", "bacod", "bacot", "bagong", "bajingan", "bangsad", "bangsat", "bastard", "bego", "bgsd", "biadab", "biadap", "bitch", "bngst", "bodoh", "bokep", "cocote", "coli", "colmek", "comli", "dajjal", "dancok", "dongo", "fuck", "gelay", "goblog", "goblok", "guoblog", "guoblok", "hairul", "henceut", "idiot", "itil", "jamet", "jancok", "jembut", "jingan", "kafir", "kanjut", "kanyut", "keparat", "kntl", "kontol", "lana", "loli", "lont", "lonte", "mancing", "meki", "memek", "ngentod", "ngentot", "ngewe", "ngocok", "ngtd", "njeng", "njing", "njinx", "oppai", "pantek", "pantek", "peler", "pepek", "pilat", "pler", "pornhub", "pucek", "puki", "pukimak", "redhub", "sange", "setan", "silit", "telaso", "tempek", "tete", "titit", "toket", "tolol", "tomlol", "tytyd", "wildan", "xnxx"],
      online: true,
      onlyprefix: '+',
      owners: ['13238004343', '5493876639332'],
      lastReset: new Date * 1,
      emoji: '⛩️',
      emoji2: '🍡',
      unlink: '~ El enlace ingresado no es válido.',
      nosear: '~ No se han encontrado resultados.',
      noapi: '~ La *API* no dio resultados.',
      sizeBot: '~ El archivo es demasiado pesado. No podrá ser enviado.',
      sucs: '*Success.*',
      erroBot: '~ Can\'t get metadata.',
      web: 'https://ko-fi.com/farguts',
      botName: '⸔ Mochi - もち ⸕',
      nameMark: 'Mochi',
      timeLoad: '⛩️',
      botDesc: 'もちツールキット *v3.0.0-rc.14*',
      dataBot: 'RedisDB',
      cliBot: '@WhiskeySockets/Baileys',
      toolks: '@mochi/toolkit',
      msg: '🍡  ¡Hola! +tag\n- Soy *Mochi*, un bot de *WhatsApp* que puede proporcionar información o utilidad al usuario. :)',
      waMenu: 'https://i.postimg.cc/Z5GcPnSv/WA-1786932310725.jpg',
      waImg: 'https://i.postimg.cc/G3gvJtFf/91fa2f7b953260940b42fff8d87b4704.jpg',
      style: 1,
      cover: 'https://i.postimg.cc/G3gvJtFf/91fa2f7b953260940b42fff8d87b4704.jpg',
      icon: null,
      link: 'https://ko-fi.com/farguts'
   }
}

export const structure = { users: [], chats: [], groups: [], instance: [], statistic: {}, sticker: {}, setting: {} }
